### ISSUE TITLE
Test failures since perl 5.17.x

### ISSUE THREAD

**Issue by eserte** [belden/perl-hash-mostutils#1]
See http://matrix.cpantesters.org/?dist=Hash-MostUtils for an overview. Maybe it's related to new warnings in these perls?

**Comment by andk** [comment]
It started to fail with https://rt.perl.org/Public/Bug/Display.html?id=120462, List::Pairwise had the same problem and has a fix for it.

And between 5.17.10 and 5.19.5? I just let the test suite run about 10 times in a row for 5.18.0 and then I got a fail. I'd bet we have a hash randomization victim as well.

**Comment by belden** [comment]
Fixed, finally: https://github.com/belden/perl-hash-mostutils/pull/5 Thanks for sending this in, um, last year.

**Comment by logie17** [comment]
:banana: :+1:
