### ISSUE TITLE
once.t test fails since 5.19.5 ($a and $b warnings)

### ISSUE THREAD

**Issue by eserte** [belden/perl-hash-mostutils#2]
The t/once.t fails with newest perls because using $main::a and $main::b does not cause a warning anymore. This is documented in perl5196delta.pod:

```
Core Enhancements
  $a and $b warnings exemption
    The special variables $a and $b, used in "sort", are now exempt from
    "used once" warnings, even where "sort" is not used. This makes it
    easier for CPAN modules to provide functions using $a and $b for similar
    purposes. [perl #120462]
```

**Comment by eserte** [comment]
The test still fails for perl 5.20.0, 5.20.1-RC1 and 5.21.x. See also http://matrix.cpantesters.org/?dist=Hash-MostUtils

**Comment by belden** [comment]
Fixed, finally: https://github.com/belden/perl-hash-mostutils/pull/5 f9a765c8245
