### ISSUE TITLE
Documentation doesn't have a DESCRIPTION section

### ISSUE THREAD

**Issue by neilb** [belden/perl-hash-mostutils#3]
Hi,

The pod doesn't have a DESCRIPTION section. This means, for example, that MetaCPAN doesn't give a summary of the module when it is included in search results. After the SYNOPSIS, the convention is to have

```
=head1 DESCRIPTION

This module provides a number of functions for processing hashes as lists of key,value pairs. Blah blah.
```

**Comment by belden** [comment]
Oh, boo me. Thanks!

**Comment by belden** [comment]
Finally fixed: https://github.com/belden/perl-hash-mostutils/pull/6
